### ISSUE TITLE
The results are in Mbps to MBps

### ISSUE THREAD

**Issue by davidworkman9** [codeforgeek/speed-test-cli#1]
For a moment I thought I was getting 3.6 Gbps speeds on my amazon EC2 server. But looking at the [speedtest-net](https://github.com/ddsol/speedtest.net) module, the data returned is in Mbps not MBps.

**Comment by shaikh-shahid** [comment]
Goodd catch. Its bit not byte. Updating it. Thanks @davidworkman9
